// Assembles the self-contained validators/<domain>.js files from src/.
// Each output file = header + generic helpers (src/common.js) + domain code.
import { readFileSync, writeFileSync } from 'node:fs';
const common = readFileSync('src/common.js', 'utf8');
const hdr = d => `// Validators for domain "${d}": V2 property(o, raw) and V3 metamorphic(run, raw, out).\n// GENERATED by build.mjs from src/ -- self-contained ES module, no imports.\n\n`;
const targets = {
  financial: readFileSync('src/financial.js', 'utf8'),
  iot: readFileSync('src/iot.js', 'utf8'),
  'usgs-corrected': 'const STRICT = false; // telos: depth in [-10,800], significance may be null\n\n' + readFileSync('src/usgs.js', 'utf8'),
  'usgs-strict': 'const STRICT = true; // telos: depth in [0,800], significance required integer\n\n' + readFileSync('src/usgs.js', 'utf8'),
};
for (const [d, src] of Object.entries(targets)) writeFileSync(`validators/${d}.js`, hdr(d) + common + '\n' + src);
console.log('built', Object.keys(targets).join(', '));
