// Validators for domain "financial": V2 property(o, raw) and V3 metamorphic(run, raw, out).
// GENERATED by build.mjs from src/ -- self-contained ES module, no imports.

// ===================================================================
// Generic helpers (shared text, inlined into every validator by build.mjs).
// They treat the raw input as an opaque string: they only look for generic
// tokens (identifiers, numbers, dates, times). No format-specific parsing.
// ===================================================================

const DAY_MS = 86400000;

function escRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// Occurrences of `tok` as a whole token, i.e. not glued to chars of class `glue`.
function tokenSpans(raw, tok, glue = 'A-Za-z0-9_\\-') {
  if (!tok) return [];
  const re = new RegExp(`(?<![${glue}])${escRe(tok)}(?![${glue}])`, 'g');
  const out = []; let m;
  while ((m = re.exec(raw))) out.push({ start: m.index, end: m.index + m[0].length });
  return out;
}

// Replace spans ({start,end,text}) in raw; spans must not overlap.
function replaceSpans(raw, spans) {
  const s = [...spans].sort((a, b) => b.start - a.start);
  let out = raw;
  for (const sp of s) out = out.slice(0, sp.start) + sp.text + out.slice(sp.end);
  return out;
}

// Blank out spans (same length) so that later scans ignore them.
function maskSpans(raw, spans) {
  return replaceSpans(raw, spans.map(s => ({ ...s, text: ' '.repeat(s.end - s.start) })));
}

// ---- numbers ------------------------------------------------------
// Every plausible numeric reading of every digit run: plain "1234.5",
// Brazilian "1.234,56", decimal comma "23,5", US grouping "1,234.56", and the
// comma-separated parts of a run (for comma-delimited lists).
// Each candidate keeps its span and style so it can be rewritten in kind.
function numberCands(raw) {
  const out = [];
  const re = /-?\d[\d.,]*/g; let m;
  while ((m = re.exec(raw))) {
    const text = m[0].replace(/[.,]+$/, '');
    const start = m.index;
    const add = (t, st, value, style) => { if (Number.isFinite(value)) out.push({ value, start: st, end: st + t.length, text: t, style }); };
    if (/^-?\d+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text), { dec: '.', thou: '', decimals: (text.split('.')[1] || '').length });
    if (/^-?\d{1,3}(\.\d{3})+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '').replace(',', '.')), { dec: ',', thou: '.', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(\.\d{3})+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '')), { dec: ',', thou: '.', decimals: 0 });
    if (/^-?\d+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(',', '.')), { dec: ',', thou: '', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(,\d{3})+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text.replace(/,/g, '')), { dec: '.', thou: ',', decimals: (text.split('.')[1] || '').length });
    // comma-separated parts (lists) -- unless the run is an unambiguous
    // Brazilian amount like "6.738,16" (grouped thousands + 1-2 decimals)
    if (text.includes(',') && !/^-?\d{1,3}(\.\d{3})+,\d{1,2}$/.test(text)) {
      let off = start;
      for (const part of text.split(',')) {
        if (/^-?\d+(\.\d+)?$/.test(part)) add(part, off, parseFloat(part), { dec: '.', thou: '', decimals: (part.split('.')[1] || '').length });
        off += part.length + 1;
      }
    }
  }
  return out;
}

// Render a number in the same style as an existing token.
function formatLike(style, v) {
  const neg = v < 0;
  let [i, f] = Math.abs(v).toFixed(style.decimals).split('.');
  if (style.thou) i = i.replace(/\B(?=(\d{3})+(?!\d))/g, style.thou);
  return (neg ? '-' : '') + i + (f !== undefined ? style.dec + f : '');
}

function close(a, b, tol) { return Math.abs(a - b) <= tol + 1e-9 * Math.max(1, Math.abs(b)); }

// ---- dates / times ------------------------------------------------
const MON = { jan: 1, feb: 2, fev: 2, ene: 1, mar: 3, apr: 4, abr: 4, may: 5, mai: 5, jun: 6, jul: 7, aug: 8, ago: 8, sep: 9, set: 9, oct: 10, out: 10, nov: 11, dec: 12, dez: 12, dic: 12 };
const pad = (n, w = 2) => String(n).padStart(w, '0');
function validYMD(y, m, d) { const t = new Date(Date.UTC(y, m - 1, d)); return t.getUTCFullYear() === y && t.getUTCMonth() === m - 1 && t.getUTCDate() === d; }
function offMinutes(z) {
  if (!z || z === 'Z') return 0;
  const m = /^([+-])(\d{2}):?(\d{2})$/.exec(z);
  return m ? (m[1] === '-' ? -1 : 1) * (Number(m[2]) * 60 + Number(m[3])) : 0;
}
function addDaysYMD(y, m, d, n) { const t = new Date(Date.UTC(y, m - 1, d + n)); return [t.getUTCFullYear(), t.getUTCMonth() + 1, t.getUTCDate()]; }

// Every date/datetime found in raw, as UTC epoch ms, with its span and a
// `shift(days)` that rewrites the token n calendar days later (same format),
// or null when that is not safely possible.
function dateCands(raw) {
  const out = []; let m;
  // ISO-like: YYYY-MM-DD[ T]HH:MM[:SS[.fff]][ ][Z|+hh:mm]
  const iso = /(?<!\d)(\d{4})([-\/])(\d{2})\2(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?)?(?!\d)/g;
  while ((m = iso.exec(raw))) {
    const [txt, Y, sep, M, D, h, mi, s, z] = m; const y = +Y, mo = +M, d = +D;
    if (!validYMD(y, mo, d)) continue;
    const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0)) - offMinutes(z) * 60000;
    out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
      shift: n => { const [a, b, c] = addDaysYMD(y, mo, d, n); return `${a}${sep}${pad(b)}${sep}${pad(c)}` + txt.slice(10); } });
  }
  // Numeric D/M/Y or M/D/Y (both readings kept when ambiguous), optional time.
  const dmy = /(?<![\d\/.\-])(\d{1,2})([\/.\-])(\d{1,2})\2(\d{4})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?(?![\d])/g;
  while ((m = dmy.exec(raw))) {
    const [txt, A, sep, B, Y, h, mi, s] = m; const a = +A, b = +B, y = +Y;
    const readings = [];
    if (validYMD(y, b, a)) readings.push([a, b, 'dmy']);
    if (a !== b && validYMD(y, a, b)) readings.push([b, a, 'mdy']);
    for (const [d, mo, kind] of readings) {
      const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0));
      const w1 = A.length, w2 = B.length, rest = txt.slice(A.length + B.length + Y.length + 2);
      out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
        shift: readings.length > 1 ? null : n => {
          const [yy, mm, dd] = addDaysYMD(y, mo, d, n);
          if (yy !== y) return null;
          const f = kind === 'dmy' ? [pad(dd, w1), pad(mm, w2)] : [pad(mm, w1), pad(dd, w2)];
          return `${f[0]}${sep}${f[1]}${sep}${yy}${rest}`;
        } });
    }
  }
  // Day + month name + year ("18-mai-2024", "18 May 2024")
  const dny = /(?<![\dA-Za-z])(\d{1,2})([-\/ .])([A-Za-zÀ-ÿ]{3,9})\.?\2(\d{4})(?!\d)/g;
  while ((m = dny.exec(raw))) {
    const [txt, D, , N, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? pad(d + n, D.length) + txt.slice(D.length) : null });
  }
  // Month name + day + year ("may-18-2024", "May 18, 2024")
  const ndy = /(?<![A-Za-zÀ-ÿ])([A-Za-zÀ-ÿ]{3,9})\.?([-\/ ])(\d{1,2}),?[-\/ ](\d{4})(?!\d)/g;
  while ((m = ndy.exec(raw))) {
    const [txt, N, , D, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    const di = txt.indexOf(D, N.length);
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? txt.slice(0, di) + pad(d + n, D.length) + txt.slice(di + D.length) : null });
  }
  // Unix epoch in seconds (10 digits) or milliseconds (13 digits)
  const ep = /(?<![\d.])(\d{13}|\d{10})(?![\d.])/g;
  while ((m = ep.exec(raw))) {
    const v = Number(m[1]); const isMs = m[1].length === 13; const ms = isMs ? v : v * 1000;
    if (ms < 9.4e11 || ms > 4.1e12) continue;
    out.push({ start: m.index, end: m.index + m[1].length, ms, hasTime: true, epoch: true,
      shift: n => String(v + n * (isMs ? DAY_MS : 86400)) });
  }
  return out;
}

// Loose clock times ("13:51:57", "07:39 -03:00") found outside date tokens;
// combined with date-only tokens to explain datetimes split over fields.
function timeTokens(masked) {
  const out = []; let m;
  const re = /(?<![\d:])(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\.\d+)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?(?![\d:])/g;
  while ((m = re.exec(masked))) {
    const h = +m[1], mi = +m[2], s = +(m[3] || 0);
    if (h > 23 || mi > 59 || s > 59) continue;
    out.push({ secs: h * 3600 + mi * 60 + s, off: m[4] ? offMinutes(m[4]) : 0 });
  }
  return out;
}

// All UTC instants (ms) that the raw string can justify.
function instantCands(raw, spanCands) {
  const set = new Set(spanCands.map(c => c.ms));
  const times = timeTokens(maskSpans(raw, spanCands));
  for (const c of spanCands) if (!c.hasTime) for (const t of times) set.add(c.ms + t.secs * 1000 - t.off * 60000);
  return set;
}

function isoSec(ms) { return new Date(Math.floor(ms / 1000) * 1000).toISOString().replace('.000Z', 'Z'); }
function dmyUTC(ms) { const t = new Date(ms); return `${pad(t.getUTCDate())}/${pad(t.getUTCMonth() + 1)}/${t.getUTCFullYear()}`; }

// Shift every date token that has a shift(); null if any cannot be shifted.
function shiftDates(raw, cands, n) {
  const spans = [];
  const seen = new Set();
  for (const c of cands) {
    const key = c.start + ':' + c.end;
    if (seen.has(key)) continue; seen.add(key);
    if (!c.shift) return null;
    const t = c.shift(n); if (t == null) return null;
    spans.push({ start: c.start, end: c.end, text: t });
  }
  // drop overlapping spans (keep the longest)
  spans.sort((a, b) => (a.start - b.start) || (b.end - a.end));
  const kept = [];
  for (const s of spans) if (!kept.length || s.start >= kept[kept.length - 1].end) kept.push(s);
  return kept.length ? replaceSpans(raw, kept) : null;
}

// ---- identifiers --------------------------------------------------
// A different token of the same shape: bump the last alphanumeric char.
function mutateId(id, raw) {
  for (let k = id.length - 1; k >= 0; k--) {
    const c = id[k]; let r = null;
    if (/[0-9]/.test(c)) r = String((+c + 1) % 10);
    else if (/[a-y]/i.test(c)) r = String.fromCharCode(c.charCodeAt(0) + 1);
    else if (c === 'z') r = 'a'; else if (c === 'Z') r = 'A';
    if (r === null) continue;
    const cand = id.slice(0, k) + r + id.slice(k + 1);
    if (!raw.includes(cand)) return cand;
  }
  return null;
}

// Safe runner: the program's output object, or null.
function safeRun(run, r) {
  try { const x = run(r); return x && typeof x === 'object' && !Array.isArray(x) ? x : null; } catch { return null; }
}

// Records equal on every key except `except` (numbers with tiny tolerance).
function sameExcept(a, b, except = []) {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const k of keys) {
    if (except.includes(k)) continue;
    const x = a[k], y = b[k];
    if (typeof x === 'number' && typeof y === 'number') { if (!close(x, y, 1e-9)) return false; }
    else if (JSON.stringify(x) !== JSON.stringify(y)) return false;
  }
  return true;
}

// ===================================================================
// Domain: financial
// ===================================================================

// ---- V0 (format-level), copied ----
function v0(o) {
  if (!o || typeof o !== 'object' || Array.isArray(o)) return false;
  if (typeof o.audit_id !== 'string' || !o.audit_id.trim()) return false;
  if (typeof o.value_in_usd !== 'number' || !Number.isFinite(o.value_in_usd) || o.value_in_usd <= 0) return false;
  if (typeof o.date !== 'string' || !/^\d{2}\/\d{2}\/\d{4}$/.test(o.date)) return false;
  const [d, m, y] = o.date.split('/').map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  if (dt.getUTCDate() !== d || dt.getUTCMonth() !== m - 1) return false;
  if (o.category !== 'domestic' && o.category !== 'international') return false;
  if (o.status !== 'valid' && o.status !== 'invalid') return false;
  return true;
}

const RATES = { BRL: 0.2, USD: 1, EUR: 1.1, GBP: 1.27 };
const VAL_TOL = 0.0051; // output may be rounded to cents

// Currency evidence: ISO codes (any case), informal names, symbols.
const CUR_PATTERNS = [
  ['BRL', /(?<![A-Za-z])(brl|reais|real)(?![A-Za-z])/gi, 'word'],
  ['BRL', /R\$/g, 'sym'],
  ['USD', /(?<![A-Za-z])(usd|d[oó]lar(?:es)?|dollars?)(?![A-Za-z])/gi, 'word'],
  ['USD', /US\$|(?<![A-Za-z])\$/g, 'sym'],
  ['EUR', /(?<![A-Za-z])(eur|euros?)(?![A-Za-z])/gi, 'word'],
  ['EUR', /€/g, 'sym'],
  ['GBP', /(?<![A-Za-z])(gbp|libras?|pounds?|sterling)(?![A-Za-z])/gi, 'word'],
  ['GBP', /£/g, 'sym'],
];
function currencyOccs(s) {
  const out = [];
  for (const [cur, re, kind] of CUR_PATTERNS) {
    re.lastIndex = 0; let m;
    while ((m = re.exec(s))) {
      const st = m.index, en = st + m[0].length;
      const standalone = kind === 'sym' || (!/[A-Za-z0-9_]/.test(s[st - 1] || '') && !/[A-Za-z0-9_]/.test(s[en] || ''));
      out.push({ cur, start: st, end: en, text: m[0], kind, standalone });
    }
  }
  return out;
}

// Shared analysis of the raw string for a given output.
function analyze(raw, o) {
  const idSpans = tokenSpans(raw, o.audit_id);
  const dates = dateCands(raw);
  const masked = maskSpans(raw, [...idSpans, ...dates]);
  const curOccs = currencyOccs(masked);
  const curs = new Set(curOccs.map(c => c.cur));
  const nums = numberCands(masked).filter(n => n.value > 0);
  // rates the category allows (BRL <-> domestic; USD value may be pre-converted)
  const rates = o.category === 'domestic'
    ? ['BRL', ...(curs.has('USD') ? ['USD'] : [])]
    : [...curs].filter(c => c !== 'BRL');
  const amountMatches = [];
  for (const n of nums) for (const c of rates) if (close(n.value * RATES[c], o.value_in_usd, VAL_TOL)) amountMatches.push({ n, cur: c });
  const utcDates = new Set([...instantCands(raw, dates)].map(dmyUTC));
  return { idSpans, dates, curOccs, curs, amountMatches, utcDates };
}

// ---- V2: property / relational validator ----
export function property(o, raw) {
  if (!v0(o) || typeof raw !== 'string') return false;
  // telos: status is always "valid" for an accepted record
  if (o.status !== 'valid') return false;
  // audit_id copied verbatim: appears as a whole token in the input
  if (o.audit_id !== o.audit_id.trim()) return false;
  const a = analyze(raw, o);
  if (!a.idSpans.length) return false;
  // missing currency => reject: some supported currency must be named
  if (!a.curs.size) return false;
  // category derived from currency (BRL => domestic, else international)
  if (o.category === 'domestic' && !a.curs.has('BRL')) return false;
  if (o.category === 'international' && ![...a.curs].some(c => c !== 'BRL')) return false;
  // value_in_usd = (positive amount in input) x (exact rate of a named currency)
  if (!a.amountMatches.length) return false;
  // date = UTC calendar date of a date/time present in the input
  if (a.utcDates.size) { if (!a.utcDates.has(o.date)) return false; }
  else if (!tokenSpans(raw, o.date.slice(6), '0-9').length) return false; // missing date => reject
  return true;
}

// ---- V3: metamorphic validator ----
const SWAP = { brl: 'eur', usd: 'eur', eur: 'gbp', gbp: 'eur', real: 'euro', dolar: 'euro', 'dólar': 'euro', dollar: 'euro', euro: 'libra', libra: 'euro', pound: 'euro' };
const NAME_CUR = { eur: 'EUR', gbp: 'GBP', euro: 'EUR', libra: 'GBP' };
function sameCase(model, s) {
  if (model === model.toUpperCase()) return s.toUpperCase();
  if (model[0] === model[0].toUpperCase()) return s[0].toUpperCase() + s.slice(1);
  return s;
}
function shiftDMY(dmy, n) { const [d, m, y] = dmy.split('/').map(Number); return dmyUTC(Date.UTC(y, m - 1, d + n)); }

export function metamorphic(run, raw, out) {
  const a = analyze(raw, out);

  // R1 identifier: renaming the id token changes only audit_id
  const newId = mutateId(out.audit_id, raw);
  if (newId && a.idSpans.length) {
    const o2 = safeRun(run, replaceSpans(raw, a.idSpans.map(s => ({ ...s, text: newId }))));
    if (!o2 || o2.audit_id !== newId || !sameExcept(out, o2, ['audit_id'])) return false;
  }

  // amount token: the unique input number that explains value_in_usd
  const spans = new Set(a.amountMatches.map(m => m.n.start + ':' + m.n.end));
  const am = spans.size === 1 ? a.amountMatches[0] : null;

  if (am) {
    // R2 linearity: doubling the amount doubles value_in_usd, nothing else changes
    const o2 = safeRun(run, replaceSpans(raw, [{ ...am.n, text: formatLike(am.n.style, am.n.value * 2) }]));
    if (!o2 || !close(o2.value_in_usd, am.n.value * 2 * RATES[am.cur], VAL_TOL) || !sameExcept(out, o2, ['value_in_usd'])) return false;
    // R3 zero amount must be rejected
    const o3 = safeRun(run, replaceSpans(raw, [{ ...am.n, text: formatLike(am.n.style, 0) }]));
    if (o3) return false;
  }

  // R4 date: moving every date token one day later moves `date` one day later
  const shifted = shiftDates(raw, a.dates, 1);
  if (shifted) {
    const o2 = safeRun(run, shifted);
    if (!o2 || o2.date !== shiftDMY(out.date, 1) || !sameExcept(out, o2, ['date'])) return false;
  }

  // Currency relations only when exactly one currency is named, in standalone tokens
  const occ = a.curOccs;
  if (a.curs.size === 1 && occ.every(c => c.standalone)) {
    // R5 swap currency word/code: rate and category follow the new currency
    if (am && occ.every(c => c.kind === 'word' && SWAP[c.text.toLowerCase()])) {
      const to = SWAP[occ[0].text.toLowerCase()];
      if (occ.every(c => SWAP[c.text.toLowerCase()] && NAME_CUR[SWAP[c.text.toLowerCase()]] === NAME_CUR[to])) {
        const cur2 = NAME_CUR[to];
        const o2 = safeRun(run, replaceSpans(raw, occ.map(c => ({ ...c, text: sameCase(c.text, SWAP[c.text.toLowerCase()]) }))));
        if (!o2 || !close(o2.value_in_usd, am.n.value * RATES[cur2], VAL_TOL) ||
            o2.category !== (cur2 === 'BRL' ? 'domestic' : 'international') ||
            !sameExcept(out, o2, ['value_in_usd', 'category'])) return false;
      }
    }
    // R6 missing currency must be rejected (never guessed)
    const o3 = safeRun(run, replaceSpans(raw, occ.map(c => ({ ...c, text: '' }))));
    if (o3) return false;
  }
  return true;
}
