// Validators for domain "iot": V2 property(o, raw) and V3 metamorphic(run, raw, out).
// GENERATED by build.mjs from src/ -- self-contained ES module, no imports.

// ===================================================================
// Generic helpers (shared text, inlined into every validator by build.mjs).
// They treat the raw input as an opaque string: they only look for generic
// tokens (identifiers, numbers, dates, times). No format-specific parsing.
// ===================================================================

const DAY_MS = 86400000;

function escRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// Occurrences of `tok` as a whole token, i.e. not glued to chars of class `glue`.
function tokenSpans(raw, tok, glue = 'A-Za-z0-9_\\-') {
  if (!tok) return [];
  const re = new RegExp(`(?<![${glue}])${escRe(tok)}(?![${glue}])`, 'g');
  const out = []; let m;
  while ((m = re.exec(raw))) out.push({ start: m.index, end: m.index + m[0].length });
  return out;
}

// Replace spans ({start,end,text}) in raw; spans must not overlap.
function replaceSpans(raw, spans) {
  const s = [...spans].sort((a, b) => b.start - a.start);
  let out = raw;
  for (const sp of s) out = out.slice(0, sp.start) + sp.text + out.slice(sp.end);
  return out;
}

// Blank out spans (same length) so that later scans ignore them.
function maskSpans(raw, spans) {
  return replaceSpans(raw, spans.map(s => ({ ...s, text: ' '.repeat(s.end - s.start) })));
}

// ---- numbers ------------------------------------------------------
// Every plausible numeric reading of every digit run: plain "1234.5",
// Brazilian "1.234,56", decimal comma "23,5", US grouping "1,234.56", and the
// comma-separated parts of a run (for comma-delimited lists).
// Each candidate keeps its span and style so it can be rewritten in kind.
function numberCands(raw) {
  const out = [];
  const re = /-?\d[\d.,]*/g; let m;
  while ((m = re.exec(raw))) {
    const text = m[0].replace(/[.,]+$/, '');
    const start = m.index;
    const add = (t, st, value, style) => { if (Number.isFinite(value)) out.push({ value, start: st, end: st + t.length, text: t, style }); };
    if (/^-?\d+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text), { dec: '.', thou: '', decimals: (text.split('.')[1] || '').length });
    if (/^-?\d{1,3}(\.\d{3})+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '').replace(',', '.')), { dec: ',', thou: '.', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(\.\d{3})+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '')), { dec: ',', thou: '.', decimals: 0 });
    if (/^-?\d+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(',', '.')), { dec: ',', thou: '', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(,\d{3})+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text.replace(/,/g, '')), { dec: '.', thou: ',', decimals: (text.split('.')[1] || '').length });
    // comma-separated parts (lists) -- unless the run is an unambiguous
    // Brazilian amount like "6.738,16" (grouped thousands + 1-2 decimals)
    if (text.includes(',') && !/^-?\d{1,3}(\.\d{3})+,\d{1,2}$/.test(text)) {
      let off = start;
      for (const part of text.split(',')) {
        if (/^-?\d+(\.\d+)?$/.test(part)) add(part, off, parseFloat(part), { dec: '.', thou: '', decimals: (part.split('.')[1] || '').length });
        off += part.length + 1;
      }
    }
  }
  return out;
}

// Render a number in the same style as an existing token.
function formatLike(style, v) {
  const neg = v < 0;
  let [i, f] = Math.abs(v).toFixed(style.decimals).split('.');
  if (style.thou) i = i.replace(/\B(?=(\d{3})+(?!\d))/g, style.thou);
  return (neg ? '-' : '') + i + (f !== undefined ? style.dec + f : '');
}

function close(a, b, tol) { return Math.abs(a - b) <= tol + 1e-9 * Math.max(1, Math.abs(b)); }

// ---- dates / times ------------------------------------------------
const MON = { jan: 1, feb: 2, fev: 2, ene: 1, mar: 3, apr: 4, abr: 4, may: 5, mai: 5, jun: 6, jul: 7, aug: 8, ago: 8, sep: 9, set: 9, oct: 10, out: 10, nov: 11, dec: 12, dez: 12, dic: 12 };
const pad = (n, w = 2) => String(n).padStart(w, '0');
function validYMD(y, m, d) { const t = new Date(Date.UTC(y, m - 1, d)); return t.getUTCFullYear() === y && t.getUTCMonth() === m - 1 && t.getUTCDate() === d; }
function offMinutes(z) {
  if (!z || z === 'Z') return 0;
  const m = /^([+-])(\d{2}):?(\d{2})$/.exec(z);
  return m ? (m[1] === '-' ? -1 : 1) * (Number(m[2]) * 60 + Number(m[3])) : 0;
}
function addDaysYMD(y, m, d, n) { const t = new Date(Date.UTC(y, m - 1, d + n)); return [t.getUTCFullYear(), t.getUTCMonth() + 1, t.getUTCDate()]; }

// Every date/datetime found in raw, as UTC epoch ms, with its span and a
// `shift(days)` that rewrites the token n calendar days later (same format),
// or null when that is not safely possible.
function dateCands(raw) {
  const out = []; let m;
  // ISO-like: YYYY-MM-DD[ T]HH:MM[:SS[.fff]][ ][Z|+hh:mm]
  const iso = /(?<!\d)(\d{4})([-\/])(\d{2})\2(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?)?(?!\d)/g;
  while ((m = iso.exec(raw))) {
    const [txt, Y, sep, M, D, h, mi, s, z] = m; const y = +Y, mo = +M, d = +D;
    if (!validYMD(y, mo, d)) continue;
    const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0)) - offMinutes(z) * 60000;
    out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
      shift: n => { const [a, b, c] = addDaysYMD(y, mo, d, n); return `${a}${sep}${pad(b)}${sep}${pad(c)}` + txt.slice(10); } });
  }
  // Numeric D/M/Y or M/D/Y (both readings kept when ambiguous), optional time.
  const dmy = /(?<![\d\/.\-])(\d{1,2})([\/.\-])(\d{1,2})\2(\d{4})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?(?![\d])/g;
  while ((m = dmy.exec(raw))) {
    const [txt, A, sep, B, Y, h, mi, s] = m; const a = +A, b = +B, y = +Y;
    const readings = [];
    if (validYMD(y, b, a)) readings.push([a, b, 'dmy']);
    if (a !== b && validYMD(y, a, b)) readings.push([b, a, 'mdy']);
    for (const [d, mo, kind] of readings) {
      const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0));
      const w1 = A.length, w2 = B.length, rest = txt.slice(A.length + B.length + Y.length + 2);
      out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
        shift: readings.length > 1 ? null : n => {
          const [yy, mm, dd] = addDaysYMD(y, mo, d, n);
          if (yy !== y) return null;
          const f = kind === 'dmy' ? [pad(dd, w1), pad(mm, w2)] : [pad(mm, w1), pad(dd, w2)];
          return `${f[0]}${sep}${f[1]}${sep}${yy}${rest}`;
        } });
    }
  }
  // Day + month name + year ("18-mai-2024", "18 May 2024")
  const dny = /(?<![\dA-Za-z])(\d{1,2})([-\/ .])([A-Za-zÀ-ÿ]{3,9})\.?\2(\d{4})(?!\d)/g;
  while ((m = dny.exec(raw))) {
    const [txt, D, , N, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? pad(d + n, D.length) + txt.slice(D.length) : null });
  }
  // Month name + day + year ("may-18-2024", "May 18, 2024")
  const ndy = /(?<![A-Za-zÀ-ÿ])([A-Za-zÀ-ÿ]{3,9})\.?([-\/ ])(\d{1,2}),?[-\/ ](\d{4})(?!\d)/g;
  while ((m = ndy.exec(raw))) {
    const [txt, N, , D, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    const di = txt.indexOf(D, N.length);
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? txt.slice(0, di) + pad(d + n, D.length) + txt.slice(di + D.length) : null });
  }
  // Unix epoch in seconds (10 digits) or milliseconds (13 digits)
  const ep = /(?<![\d.])(\d{13}|\d{10})(?![\d.])/g;
  while ((m = ep.exec(raw))) {
    const v = Number(m[1]); const isMs = m[1].length === 13; const ms = isMs ? v : v * 1000;
    if (ms < 9.4e11 || ms > 4.1e12) continue;
    out.push({ start: m.index, end: m.index + m[1].length, ms, hasTime: true, epoch: true,
      shift: n => String(v + n * (isMs ? DAY_MS : 86400)) });
  }
  return out;
}

// Loose clock times ("13:51:57", "07:39 -03:00") found outside date tokens;
// combined with date-only tokens to explain datetimes split over fields.
function timeTokens(masked) {
  const out = []; let m;
  const re = /(?<![\d:])(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\.\d+)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?(?![\d:])/g;
  while ((m = re.exec(masked))) {
    const h = +m[1], mi = +m[2], s = +(m[3] || 0);
    if (h > 23 || mi > 59 || s > 59) continue;
    out.push({ secs: h * 3600 + mi * 60 + s, off: m[4] ? offMinutes(m[4]) : 0 });
  }
  return out;
}

// All UTC instants (ms) that the raw string can justify.
function instantCands(raw, spanCands) {
  const set = new Set(spanCands.map(c => c.ms));
  const times = timeTokens(maskSpans(raw, spanCands));
  for (const c of spanCands) if (!c.hasTime) for (const t of times) set.add(c.ms + t.secs * 1000 - t.off * 60000);
  return set;
}

function isoSec(ms) { return new Date(Math.floor(ms / 1000) * 1000).toISOString().replace('.000Z', 'Z'); }
function dmyUTC(ms) { const t = new Date(ms); return `${pad(t.getUTCDate())}/${pad(t.getUTCMonth() + 1)}/${t.getUTCFullYear()}`; }

// Shift every date token that has a shift(); null if any cannot be shifted.
function shiftDates(raw, cands, n) {
  const spans = [];
  const seen = new Set();
  for (const c of cands) {
    const key = c.start + ':' + c.end;
    if (seen.has(key)) continue; seen.add(key);
    if (!c.shift) return null;
    const t = c.shift(n); if (t == null) return null;
    spans.push({ start: c.start, end: c.end, text: t });
  }
  // drop overlapping spans (keep the longest)
  spans.sort((a, b) => (a.start - b.start) || (b.end - a.end));
  const kept = [];
  for (const s of spans) if (!kept.length || s.start >= kept[kept.length - 1].end) kept.push(s);
  return kept.length ? replaceSpans(raw, kept) : null;
}

// ---- identifiers --------------------------------------------------
// A different token of the same shape: bump the last alphanumeric char.
function mutateId(id, raw) {
  for (let k = id.length - 1; k >= 0; k--) {
    const c = id[k]; let r = null;
    if (/[0-9]/.test(c)) r = String((+c + 1) % 10);
    else if (/[a-y]/i.test(c)) r = String.fromCharCode(c.charCodeAt(0) + 1);
    else if (c === 'z') r = 'a'; else if (c === 'Z') r = 'A';
    if (r === null) continue;
    const cand = id.slice(0, k) + r + id.slice(k + 1);
    if (!raw.includes(cand)) return cand;
  }
  return null;
}

// Safe runner: the program's output object, or null.
function safeRun(run, r) {
  try { const x = run(r); return x && typeof x === 'object' && !Array.isArray(x) ? x : null; } catch { return null; }
}

// Records equal on every key except `except` (numbers with tiny tolerance).
function sameExcept(a, b, except = []) {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const k of keys) {
    if (except.includes(k)) continue;
    const x = a[k], y = b[k];
    if (typeof x === 'number' && typeof y === 'number') { if (!close(x, y, 1e-9)) return false; }
    else if (JSON.stringify(x) !== JSON.stringify(y)) return false;
  }
  return true;
}

// ===================================================================
// Domain: iot
// ===================================================================

// ---- V0 (format-level), copied ----
const METRICS = ['temperature', 'humidity', 'pressure'];
const ZONES = ['north', 'south', 'east', 'west'];
const TS_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;
const RANGES = { temperature: [-60, 70], humidity: [0, 100], pressure: [850, 1100] };
function v0(o) {
  if (!o || typeof o !== 'object' || Array.isArray(o)) return false;
  if (typeof o.device_id !== 'string' || !o.device_id.trim()) return false;
  if (!METRICS.includes(o.metric)) return false;
  if (typeof o.value !== 'number' || !Number.isFinite(o.value)) return false;
  const [lo, hi] = RANGES[o.metric];
  if (o.value < lo || o.value > hi) return false;
  if (typeof o.timestamp_utc !== 'string' || !TS_RE.test(o.timestamp_utc) || isNaN(Date.parse(o.timestamp_utc))) return false;
  if (!['normal', 'warning', 'critical'].includes(o.status)) return false;
  if (!ZONES.includes(o.zone)) return false;
  return true;
}
function statusOf(metric, v) {
  if (metric === 'temperature') return v > 40 || v < -5 ? 'critical' : v > 30 || v < 0 ? 'warning' : 'normal';
  if (metric === 'humidity') return v > 90 ? 'critical' : v > 75 ? 'warning' : 'normal';
  return v < 960 || v > 1040 ? 'critical' : v < 980 || v > 1030 ? 'warning' : 'normal';
}

// ---- evidence in the raw string ----
const METRIC_EV = {
  temperature: /(?<![A-Za-z])(temp|therm)/i,
  humidity: /(?<![A-Za-z])(hum|umid|rh(?![A-Za-z]))/i,
  pressure: /(?<![A-Za-z])(press|baro)/i,
};
// a single capital letter standing alone as a token (e.g. "|F|", "311.92,K")
const letter = (s, c) => new RegExp(`(?<![A-Za-z0-9_\\-])${c}(?![A-Za-z0-9_\\-])`).test(s);
const UNIT_EV = {
  C: s => /[°º]\s?C|celsius|centigrad|degC/i.test(s) || letter(s, 'C'),
  F: s => /[°º]\s?F|fahrenheit|degF/i.test(s) || letter(s, 'F'),
  K: s => /[°º]\s?K|kelvin/i.test(s) || letter(s, 'K'),
  kPa: s => /kpa/i.test(s),
  hPa: s => /hpa|mbar|millibar/i.test(s),
  Pa: s => /pascal/i.test(s) || /(?<![A-Za-z0-9_\-])Pa(?![A-Za-z])/.test(s),
};

// Conversions to the canonical unit that the unit evidence allows.
function conversions(metric, s) {
  const has = k => UNIT_EV[k](s);
  const out = [];
  if (metric === 'temperature') {
    if (has('C') || (!has('F') && !has('K'))) out.push(['C', x => x]);
    if (has('F')) out.push(['F', x => (x - 32) * 5 / 9]);
    if (has('K')) out.push(['K', x => x - 273.15]);
  } else if (metric === 'humidity') out.push(['%', x => x]);
  else {
    if (has('hPa') || (!has('kPa') && !has('Pa'))) out.push(['hPa', x => x]);
    if (has('kPa')) out.push(['kPa', x => x * 10]);
  }
  return out;
}

// Zone tokens: words (en/pt), single letters N/S/E/W, vendor zone-A..D.
const ZONE_PATTERNS = [
  [/(?<![A-Za-z])(north|norte)(?![A-Za-z])/gi, 'north'], [/(?<![A-Za-z])(south|sul)(?![A-Za-z])/gi, 'south'],
  [/(?<![A-Za-z])(east|leste)(?![A-Za-z])/gi, 'east'], [/(?<![A-Za-z])(west|oeste)(?![A-Za-z])/gi, 'west'],
  [/(?<![A-Za-z0-9_\-])N(?![A-Za-z0-9_\-])/g, 'north'], [/(?<![A-Za-z0-9_\-])S(?![A-Za-z0-9_\-])/g, 'south'],
  [/(?<![A-Za-z0-9_\-])E(?![A-Za-z0-9_\-])/g, 'east'], [/(?<![A-Za-z0-9_\-])W(?![A-Za-z0-9_\-])/g, 'west'],
];
const VENDOR = { a: 'north', b: 'south', c: 'east', d: 'west' };
function zoneOccs(s) {
  const out = [];
  for (const [re, zone] of ZONE_PATTERNS) { re.lastIndex = 0; let m; while ((m = re.exec(s))) out.push({ zone, start: m.index, end: m.index + m[0].length, text: m[0] }); }
  const vre = /(?<![A-Za-z])zone[\s_\-]?([A-Da-d])(?![A-Za-z0-9])/gi; let m;
  while ((m = vre.exec(s))) out.push({ zone: VENDOR[m[1].toLowerCase()], start: m.index, end: m.index + m[0].length, text: m[0], vendor: true });
  return out;
}
const ZONE_SWAP_WORD = { north: 'south', south: 'north', east: 'west', west: 'east', norte: 'sul', sul: 'norte', leste: 'oeste', oeste: 'leste' };
const ZONE_SWAP_LETTER = { N: 'S', S: 'N', E: 'W', W: 'E', A: 'B', B: 'A', C: 'D', D: 'C', a: 'b', b: 'a', c: 'd', d: 'c' };
function swapZoneText(t, vendor) {
  if (vendor) return t.slice(0, -1) + ZONE_SWAP_LETTER[t.slice(-1)];
  if (t.length === 1) return ZONE_SWAP_LETTER[t];
  const w = ZONE_SWAP_WORD[t.toLowerCase()];
  return t === t.toUpperCase() ? w.toUpperCase() : t[0] === t[0].toUpperCase() ? w[0].toUpperCase() + w.slice(1) : w;
}
const OTHER_ZONE = { north: 'south', south: 'north', east: 'west', west: 'east' };

const round2 = x => Math.round(x * 100) / 100;
const VAL_TOL = 0.00501;

function analyze(raw, o) {
  const idSpans = tokenSpans(raw, o.device_id);
  const dates = dateCands(raw);
  const masked = maskSpans(raw, [...idSpans, ...dates]);
  const convs = METRICS.includes(o.metric) ? conversions(o.metric, masked) : [];
  const nums = numberCands(masked);
  const valueMatches = [];
  for (const n of nums) for (const [u, f] of convs) if (close(f(n.value), o.value, VAL_TOL)) valueMatches.push({ n, u, f });
  const instants = new Set([...instantCands(raw, dates)].map(isoSec));
  return { idSpans, dates, masked, valueMatches, instants, zones: zoneOccs(masked) };
}

// ---- V2: property / relational validator ----
export function property(o, raw) {
  if (!v0(o) || typeof raw !== 'string') return false;
  // status is derived from the canonical value
  if (o.status !== statusOf(o.metric, o.value)) return false;
  // value rounded to 2 decimals
  if (Math.abs(o.value * 100 - Math.round(o.value * 100)) > 1e-6) return false;
  // device_id copied verbatim: whole token in the input
  if (o.device_id !== o.device_id.trim()) return false;
  const a = analyze(raw, o);
  if (!a.idSpans.length) return false;
  // missing metric => reject: the metric (or its abbreviation) is named in the input
  if (!METRIC_EV[o.metric].test(a.masked)) return false;
  // missing zone => reject: the output zone is named (word, letter or vendor zone)
  if (!a.zones.some(z => z.zone === o.zone)) return false;
  // value = unit conversion (allowed by the input's unit evidence) of an input number
  if (!a.valueMatches.length) return false;
  // timestamp_utc = an instant (date [+ time] [+ offset], or epoch) present in the input
  if (a.instants.size) { if (!a.instants.has(o.timestamp_utc)) return false; }
  else if (!tokenSpans(raw, o.timestamp_utc.slice(0, 4), '0-9').length) return false;
  return true;
}

// ---- V3: metamorphic validator ----
export function metamorphic(run, raw, out) {
  const a = analyze(raw, out);

  // R1 identifier: renaming the device token changes only device_id
  const newId = mutateId(out.device_id, raw);
  if (newId && a.idSpans.length) {
    const o2 = safeRun(run, replaceSpans(raw, a.idSpans.map(s => ({ ...s, text: newId }))));
    if (!o2 || o2.device_id !== newId || !sameExcept(out, o2, ['device_id'])) return false;
  }

  // value token: unique input number (with a unique conversion) explaining value
  const spans = new Set(a.valueMatches.map(m => m.n.start + ':' + m.n.end));
  const vm = spans.size === 1 && new Set(a.valueMatches.map(m => m.u)).size === 1 ? a.valueMatches[0] : null;
  if (vm) {
    // R2 conversion follows the input: raw+1 => conv(raw+1); status re-derived
    const [lo, hi] = RANGES[out.metric];
    let n2 = vm.n.value + 1;
    if (vm.f(n2) > hi - 1) n2 = vm.n.value - 1;
    const exp = vm.f(n2);
    if (exp >= lo && exp <= hi) {
      const o2 = safeRun(run, replaceSpans(raw, [{ ...vm.n, text: formatLike(vm.n.style, n2) }]));
      if (!o2 || !close(o2.value, exp, VAL_TOL) || o2.status !== statusOf(out.metric, o2.value) ||
          !sameExcept(out, o2, ['value', 'status'])) return false;
    }
    // R3 physically impossible value must be rejected
    const o3 = safeRun(run, replaceSpans(raw, [{ ...vm.n, text: formatLike(vm.n.style, 9999) }]));
    if (o3) return false;
  }

  // R4 time: every date token one day later => timestamp_utc exactly +24h
  const shifted = shiftDates(raw, a.dates, 1);
  if (shifted) {
    const o2 = safeRun(run, shifted);
    if (!o2 || o2.timestamp_utc !== isoSec(Date.parse(out.timestamp_utc) + DAY_MS) || !sameExcept(out, o2, ['timestamp_utc'])) return false;
  }

  // R5 zone: swapping the (unambiguous) zone token swaps only the zone
  const mine = a.zones.filter(z => z.zone === out.zone);
  if (mine.length && a.zones.length === mine.length) {
    const o2 = safeRun(run, replaceSpans(raw, mine.map(z => ({ ...z, text: swapZoneText(z.text, z.vendor) }))));
    if (!o2 || o2.zone !== OTHER_ZONE[out.zone] || !sameExcept(out, o2, ['zone'])) return false;
  }
  return true;
}
