// Validators for domain "usgs-strict": V2 property(o, raw) and V3 metamorphic(run, raw, out).
// GENERATED by build.mjs from src/ -- self-contained ES module, no imports.

// ===================================================================
// Generic helpers (shared text, inlined into every validator by build.mjs).
// They treat the raw input as an opaque string: they only look for generic
// tokens (identifiers, numbers, dates, times). No format-specific parsing.
// ===================================================================

const DAY_MS = 86400000;

function escRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// Occurrences of `tok` as a whole token, i.e. not glued to chars of class `glue`.
function tokenSpans(raw, tok, glue = 'A-Za-z0-9_\\-') {
  if (!tok) return [];
  const re = new RegExp(`(?<![${glue}])${escRe(tok)}(?![${glue}])`, 'g');
  const out = []; let m;
  while ((m = re.exec(raw))) out.push({ start: m.index, end: m.index + m[0].length });
  return out;
}

// Replace spans ({start,end,text}) in raw; spans must not overlap.
function replaceSpans(raw, spans) {
  const s = [...spans].sort((a, b) => b.start - a.start);
  let out = raw;
  for (const sp of s) out = out.slice(0, sp.start) + sp.text + out.slice(sp.end);
  return out;
}

// Blank out spans (same length) so that later scans ignore them.
function maskSpans(raw, spans) {
  return replaceSpans(raw, spans.map(s => ({ ...s, text: ' '.repeat(s.end - s.start) })));
}

// ---- numbers ------------------------------------------------------
// Every plausible numeric reading of every digit run: plain "1234.5",
// Brazilian "1.234,56", decimal comma "23,5", US grouping "1,234.56", and the
// comma-separated parts of a run (for comma-delimited lists).
// Each candidate keeps its span and style so it can be rewritten in kind.
function numberCands(raw) {
  const out = [];
  const re = /-?\d[\d.,]*/g; let m;
  while ((m = re.exec(raw))) {
    const text = m[0].replace(/[.,]+$/, '');
    const start = m.index;
    const add = (t, st, value, style) => { if (Number.isFinite(value)) out.push({ value, start: st, end: st + t.length, text: t, style }); };
    if (/^-?\d+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text), { dec: '.', thou: '', decimals: (text.split('.')[1] || '').length });
    if (/^-?\d{1,3}(\.\d{3})+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '').replace(',', '.')), { dec: ',', thou: '.', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(\.\d{3})+$/.test(text)) add(text, start, parseFloat(text.replace(/\./g, '')), { dec: ',', thou: '.', decimals: 0 });
    if (/^-?\d+,\d+$/.test(text)) add(text, start, parseFloat(text.replace(',', '.')), { dec: ',', thou: '', decimals: text.split(',')[1].length });
    if (/^-?\d{1,3}(,\d{3})+(\.\d+)?$/.test(text)) add(text, start, parseFloat(text.replace(/,/g, '')), { dec: '.', thou: ',', decimals: (text.split('.')[1] || '').length });
    // comma-separated parts (lists) -- unless the run is an unambiguous
    // Brazilian amount like "6.738,16" (grouped thousands + 1-2 decimals)
    if (text.includes(',') && !/^-?\d{1,3}(\.\d{3})+,\d{1,2}$/.test(text)) {
      let off = start;
      for (const part of text.split(',')) {
        if (/^-?\d+(\.\d+)?$/.test(part)) add(part, off, parseFloat(part), { dec: '.', thou: '', decimals: (part.split('.')[1] || '').length });
        off += part.length + 1;
      }
    }
  }
  return out;
}

// Render a number in the same style as an existing token.
function formatLike(style, v) {
  const neg = v < 0;
  let [i, f] = Math.abs(v).toFixed(style.decimals).split('.');
  if (style.thou) i = i.replace(/\B(?=(\d{3})+(?!\d))/g, style.thou);
  return (neg ? '-' : '') + i + (f !== undefined ? style.dec + f : '');
}

function close(a, b, tol) { return Math.abs(a - b) <= tol + 1e-9 * Math.max(1, Math.abs(b)); }

// ---- dates / times ------------------------------------------------
const MON = { jan: 1, feb: 2, fev: 2, ene: 1, mar: 3, apr: 4, abr: 4, may: 5, mai: 5, jun: 6, jul: 7, aug: 8, ago: 8, sep: 9, set: 9, oct: 10, out: 10, nov: 11, dec: 12, dez: 12, dic: 12 };
const pad = (n, w = 2) => String(n).padStart(w, '0');
function validYMD(y, m, d) { const t = new Date(Date.UTC(y, m - 1, d)); return t.getUTCFullYear() === y && t.getUTCMonth() === m - 1 && t.getUTCDate() === d; }
function offMinutes(z) {
  if (!z || z === 'Z') return 0;
  const m = /^([+-])(\d{2}):?(\d{2})$/.exec(z);
  return m ? (m[1] === '-' ? -1 : 1) * (Number(m[2]) * 60 + Number(m[3])) : 0;
}
function addDaysYMD(y, m, d, n) { const t = new Date(Date.UTC(y, m - 1, d + n)); return [t.getUTCFullYear(), t.getUTCMonth() + 1, t.getUTCDate()]; }

// Every date/datetime found in raw, as UTC epoch ms, with its span and a
// `shift(days)` that rewrites the token n calendar days later (same format),
// or null when that is not safely possible.
function dateCands(raw) {
  const out = []; let m;
  // ISO-like: YYYY-MM-DD[ T]HH:MM[:SS[.fff]][ ][Z|+hh:mm]
  const iso = /(?<!\d)(\d{4})([-\/])(\d{2})\2(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.\d+)?)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?)?(?!\d)/g;
  while ((m = iso.exec(raw))) {
    const [txt, Y, sep, M, D, h, mi, s, z] = m; const y = +Y, mo = +M, d = +D;
    if (!validYMD(y, mo, d)) continue;
    const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0)) - offMinutes(z) * 60000;
    out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
      shift: n => { const [a, b, c] = addDaysYMD(y, mo, d, n); return `${a}${sep}${pad(b)}${sep}${pad(c)}` + txt.slice(10); } });
  }
  // Numeric D/M/Y or M/D/Y (both readings kept when ambiguous), optional time.
  const dmy = /(?<![\d\/.\-])(\d{1,2})([\/.\-])(\d{1,2})\2(\d{4})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?(?![\d])/g;
  while ((m = dmy.exec(raw))) {
    const [txt, A, sep, B, Y, h, mi, s] = m; const a = +A, b = +B, y = +Y;
    const readings = [];
    if (validYMD(y, b, a)) readings.push([a, b, 'dmy']);
    if (a !== b && validYMD(y, a, b)) readings.push([b, a, 'mdy']);
    for (const [d, mo, kind] of readings) {
      const ms = Date.UTC(y, mo - 1, d, +(h || 0), +(mi || 0), +(s || 0));
      const w1 = A.length, w2 = B.length, rest = txt.slice(A.length + B.length + Y.length + 2);
      out.push({ start: m.index, end: m.index + txt.length, ms, hasTime: h !== undefined,
        shift: readings.length > 1 ? null : n => {
          const [yy, mm, dd] = addDaysYMD(y, mo, d, n);
          if (yy !== y) return null;
          const f = kind === 'dmy' ? [pad(dd, w1), pad(mm, w2)] : [pad(mm, w1), pad(dd, w2)];
          return `${f[0]}${sep}${f[1]}${sep}${yy}${rest}`;
        } });
    }
  }
  // Day + month name + year ("18-mai-2024", "18 May 2024")
  const dny = /(?<![\dA-Za-z])(\d{1,2})([-\/ .])([A-Za-zÀ-ÿ]{3,9})\.?\2(\d{4})(?!\d)/g;
  while ((m = dny.exec(raw))) {
    const [txt, D, , N, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? pad(d + n, D.length) + txt.slice(D.length) : null });
  }
  // Month name + day + year ("may-18-2024", "May 18, 2024")
  const ndy = /(?<![A-Za-zÀ-ÿ])([A-Za-zÀ-ÿ]{3,9})\.?([-\/ ])(\d{1,2}),?[-\/ ](\d{4})(?!\d)/g;
  while ((m = ndy.exec(raw))) {
    const [txt, N, , D, Y] = m; const mo = MON[N.slice(0, 3).toLowerCase()], d = +D, y = +Y;
    if (!mo || !validYMD(y, mo, d)) continue;
    const di = txt.indexOf(D, N.length);
    out.push({ start: m.index, end: m.index + txt.length, ms: Date.UTC(y, mo - 1, d), hasTime: false,
      shift: n => validYMD(y, mo, d + n) ? txt.slice(0, di) + pad(d + n, D.length) + txt.slice(di + D.length) : null });
  }
  // Unix epoch in seconds (10 digits) or milliseconds (13 digits)
  const ep = /(?<![\d.])(\d{13}|\d{10})(?![\d.])/g;
  while ((m = ep.exec(raw))) {
    const v = Number(m[1]); const isMs = m[1].length === 13; const ms = isMs ? v : v * 1000;
    if (ms < 9.4e11 || ms > 4.1e12) continue;
    out.push({ start: m.index, end: m.index + m[1].length, ms, hasTime: true, epoch: true,
      shift: n => String(v + n * (isMs ? DAY_MS : 86400)) });
  }
  return out;
}

// Loose clock times ("13:51:57", "07:39 -03:00") found outside date tokens;
// combined with date-only tokens to explain datetimes split over fields.
function timeTokens(masked) {
  const out = []; let m;
  const re = /(?<![\d:])(\d{1,2}):(\d{2})(?::(\d{2}))?(?:\.\d+)?(?:\s?(Z|[+-]\d{2}:?\d{2})(?![\d:]))?(?![\d:])/g;
  while ((m = re.exec(masked))) {
    const h = +m[1], mi = +m[2], s = +(m[3] || 0);
    if (h > 23 || mi > 59 || s > 59) continue;
    out.push({ secs: h * 3600 + mi * 60 + s, off: m[4] ? offMinutes(m[4]) : 0 });
  }
  return out;
}

// All UTC instants (ms) that the raw string can justify.
function instantCands(raw, spanCands) {
  const set = new Set(spanCands.map(c => c.ms));
  const times = timeTokens(maskSpans(raw, spanCands));
  for (const c of spanCands) if (!c.hasTime) for (const t of times) set.add(c.ms + t.secs * 1000 - t.off * 60000);
  return set;
}

function isoSec(ms) { return new Date(Math.floor(ms / 1000) * 1000).toISOString().replace('.000Z', 'Z'); }
function dmyUTC(ms) { const t = new Date(ms); return `${pad(t.getUTCDate())}/${pad(t.getUTCMonth() + 1)}/${t.getUTCFullYear()}`; }

// Shift every date token that has a shift(); null if any cannot be shifted.
function shiftDates(raw, cands, n) {
  const spans = [];
  const seen = new Set();
  for (const c of cands) {
    const key = c.start + ':' + c.end;
    if (seen.has(key)) continue; seen.add(key);
    if (!c.shift) return null;
    const t = c.shift(n); if (t == null) return null;
    spans.push({ start: c.start, end: c.end, text: t });
  }
  // drop overlapping spans (keep the longest)
  spans.sort((a, b) => (a.start - b.start) || (b.end - a.end));
  const kept = [];
  for (const s of spans) if (!kept.length || s.start >= kept[kept.length - 1].end) kept.push(s);
  return kept.length ? replaceSpans(raw, kept) : null;
}

// ---- identifiers --------------------------------------------------
// A different token of the same shape: bump the last alphanumeric char.
function mutateId(id, raw) {
  for (let k = id.length - 1; k >= 0; k--) {
    const c = id[k]; let r = null;
    if (/[0-9]/.test(c)) r = String((+c + 1) % 10);
    else if (/[a-y]/i.test(c)) r = String.fromCharCode(c.charCodeAt(0) + 1);
    else if (c === 'z') r = 'a'; else if (c === 'Z') r = 'A';
    if (r === null) continue;
    const cand = id.slice(0, k) + r + id.slice(k + 1);
    if (!raw.includes(cand)) return cand;
  }
  return null;
}

// Safe runner: the program's output object, or null.
function safeRun(run, r) {
  try { const x = run(r); return x && typeof x === 'object' && !Array.isArray(x) ? x : null; } catch { return null; }
}

// Records equal on every key except `except` (numbers with tiny tolerance).
function sameExcept(a, b, except = []) {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const k of keys) {
    if (except.includes(k)) continue;
    const x = a[k], y = b[k];
    if (typeof x === 'number' && typeof y === 'number') { if (!close(x, y, 1e-9)) return false; }
    else if (JSON.stringify(x) !== JSON.stringify(y)) return false;
  }
  return true;
}

const STRICT = true; // telos: depth in [0,800], significance required integer

// ===================================================================
// Domain: usgs-corrected / usgs-strict (STRICT is set per file by build)
// ===================================================================

// ---- V0 (format-level), copied. baseValid was not shown in the V0 file;
// it is reconstructed from the telos field list (see NOTES.md). ----
const MAG_TYPES = new Set(['ml', 'md', 'mb', 'mw', 'mww', 'mwb', 'mwc', 'mwr', 'ms', 'mb_lg', 'mi', 'mh']);
const TS_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;
function baseValid(o) {
  if (!o || typeof o !== 'object' || Array.isArray(o)) return false;
  if (typeof o.event_id !== 'string' || !o.event_id.trim()) return false;
  if (typeof o.magnitude !== 'number' || !Number.isFinite(o.magnitude)) return false;
  if (!MAG_TYPES.has(o.magnitude_type)) return false;
  if (typeof o.latitude !== 'number' || !(o.latitude >= -90 && o.latitude <= 90)) return false;
  if (typeof o.longitude !== 'number' || !(o.longitude >= -180 && o.longitude <= 180)) return false;
  if (typeof o.timestamp_utc !== 'string' || !TS_RE.test(o.timestamp_utc) || isNaN(Date.parse(o.timestamp_utc))) return false;
  if (typeof o.place !== 'string' || !o.place.trim()) return false;
  if (typeof o.event_type !== 'string') return false;
  if (o.status !== 'reviewed' && o.status !== 'automatic') return false;
  return true;
}
function validatorCorrected(o) {
  if (!baseValid(o)) return false;
  if (typeof o.depth_km !== 'number' || o.depth_km < -10 || o.depth_km > 800) return false;
  if (o.significance !== null && (!Number.isInteger(o.significance) || o.significance < 0 || o.significance > 2500)) return false;
  return true;
}
function validatorOriginal(o) {
  if (!baseValid(o)) return false;
  if (typeof o.depth_km !== 'number' || o.depth_km < 0 || o.depth_km > 800) return false;
  if (!Number.isInteger(o.significance) || o.significance < 0 || o.significance > 2500) return false;
  return true;
}
const v0 = o => (STRICT ? validatorOriginal(o) : validatorCorrected(o));

// ---- generic evidence ----
// Whole numeric tokens (JSON / CSV / XML-safe boundaries) with their spans.
function numTokens(raw) {
  const out = []; const re = /(?<![\w.])-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?(?![\w.])/g; let m;
  while ((m = re.exec(raw))) out.push({ value: Number(m[0]), text: m[0], start: m.index, end: m.index + m[0].length, idx: out.length });
  return out;
}
const spansOf = (nums, v) => nums.filter(n => close(n.value, v, 1e-9));
// "sig" key followed by its value (the telos names the source field "sig")
function sigField(raw) {
  const m = /(?<![A-Za-z])sig(?![A-Za-z])[^A-Za-z0-9\-]{1,4}(-?\d+(?:\.\d+)?|null)/i.exec(raw);
  if (!m) return { word: /(?<![A-Za-z])sig(?![A-Za-z])/i.test(raw), val: undefined };
  const start = m.index + m[0].length - m[1].length;
  return { word: true, val: m[1] === 'null' ? null : Number(m[1]), start, end: start + m[1].length, text: m[1] };
}
// All alphanumeric runs of the input.
const alnumRuns = raw => raw.match(/[A-Za-z0-9_]+/g) || [];
// Place strings may be JSON-escaped or CSV-quoted in the input.
function containsVerbatim(raw, s) {
  return raw.includes(s) || raw.includes(JSON.stringify(s).slice(1, -1)) || raw.includes(s.replace(/"/g, '""'));
}
const GEOJSON_STRUCT = new Set(['Feature', 'FeatureCollection', 'Point', 'Geometry']);

// Distinct-token assignment for [magnitude, latitude, longitude, depth]:
// each field needs its own token, and lat/lon/depth must be a location group
// (within a few numeric tokens of each other, as the coordinate triple is).
const NEAR = 4;
function assignDistinct(lists, pick = []) {
  const i = pick.length;
  if (i === lists.length) {
    const [, la, lo, de] = pick;
    return Math.abs(la.idx - lo.idx) <= NEAR && Math.abs(de.idx - la.idx) <= NEAR && Math.abs(de.idx - lo.idx) <= NEAR;
  }
  for (const t of lists[i]) if (!pick.some(p => p.start === t.start) && assignDistinct(lists, [...pick, t])) return true;
  return false;
}

function analyze(raw, o) {
  const nums = numTokens(raw);
  const dates = dateCands(raw).filter(c => c.hasTime);
  const instants = [...new Set(dates.map(c => isoSec(c.ms)))].sort();
  return { nums, dates, instants, sig: sigField(raw) };
}

// ---- V2: property / relational validator ----
export function property(o, raw) {
  if (!v0(o) || typeof raw !== 'string') return false;
  const a = analyze(raw, o);
  // event_id verbatim, and the full id (net+code), not a fragment of a longer token
  if (!tokenSpans(raw, o.event_id, 'A-Za-z0-9_').length) return false;
  if (alnumRuns(raw).some(r => r !== o.event_id && r.includes(o.event_id))) return false;
  // magnitude_type is the input's magType lowercased
  if (!tokenSpans(raw.toLowerCase(), o.magnitude_type, 'A-Za-z0-9_').length) return false;
  // magnitude, latitude, longitude, depth copied from input numbers, each from its own
  // token; lat/lon/depth adjacent (coordinate triple)
  const lists = [o.magnitude, o.latitude, o.longitude, o.depth_km].map(v => spansOf(a.nums, v));
  if (lists.some(l => !l.length) || !assignDistinct(lists)) return false;
  if (o.latitude === o.longitude && lists[1].length < 2) return false;
  // place verbatim; not the "M x.y - place" title
  if (!containsVerbatim(raw, o.place) || !/[A-Za-z]/.test(o.place)) return false;
  const t = /^M\s*-?\d+(?:\.\d+)?\s+-\s+(.+)$/.exec(o.place);
  if (t && containsVerbatim(raw, t[1])) return false;
  // event_type verbatim, not a GeoJSON structural word, not another field
  if (!o.event_type.trim() || !containsVerbatim(raw, o.event_type) || GEOJSON_STRUCT.has(o.event_type)) return false;
  if (o.event_type === o.place || o.event_type === o.status) return false;
  // status is stated in the input
  if (!tokenSpans(raw.toLowerCase(), o.status, 'A-Za-z').length) return false;
  // timestamp = origin time: an instant in the input, and the earliest one (updated >= time)
  if (a.instants.length) { if (o.timestamp_utc !== a.instants[0]) return false; }
  else if (!tokenSpans(raw, o.timestamp_utc.slice(0, 4), '0-9').length) return false;
  // significance taken from "sig"; corrected: null iff no such field; strict: must exist
  if (STRICT) {
    if (typeof a.sig.val !== 'number' || o.significance !== a.sig.val) return false;
  } else if (a.sig.val !== undefined) {
    if (o.significance !== a.sig.val) return false;
  } else if (a.sig.word) {
    if (o.significance !== null && !spansOf(a.nums, o.significance).length) return false;
  } else if (o.significance !== null) return false;
  return true;
}

// ---- V3: metamorphic validator ----
function bumpText(text, delta) {
  const dec = (text.split('.')[1] || '').length;
  return (Number(text) + delta).toFixed(dec);
}
const negText = t => (t.startsWith('-') ? t.slice(1) : '-' + t);

export function metamorphic(run, raw, out) {
  const a = analyze(raw, out);
  const KEEP = ['event_id', 'magnitude', 'magnitude_type', 'latitude', 'longitude', 'timestamp_utc', 'place', 'event_type', 'status', 'depth_km', 'significance'];
  const only = (o2, changed) => sameExcept(out, o2, [...Object.keys(out).filter(k => !KEEP.includes(k)), ...changed]);

  // R1 identifier: renaming the id token changes only event_id
  const newId = mutateId(out.event_id, raw);
  const idSpans = tokenSpans(raw, out.event_id, 'A-Za-z0-9_');
  if (newId && idSpans.length) {
    const o2 = safeRun(run, replaceSpans(raw, idSpans.map(s => ({ ...s, text: newId }))));
    if (!o2 || o2.event_id !== newId || !only(o2, ['event_id'])) return false;
  }

  // R2 magnitude +1 and depth changed: both follow the input verbatim
  const magS = spansOf(a.nums, out.magnitude), depS = spansOf(a.nums, out.depth_km);
  const latS = spansOf(a.nums, out.latitude), lonS = spansOf(a.nums, out.longitude);
  const coordStarts = new Set([...latS, ...lonS].map(s => s.start));
  if (magS.length && !magS.some(s => coordStarts.has(s.start))) {
    const edits = magS.map(s => ({ ...s, text: bumpText(s.text, 1) }));
    const newMag = Number(edits[0].text);
    let newDepth = null;
    if (depS.length === 1 && !magS.some(s => s.start === depS[0].start) && !coordStarts.has(depS[0].start)) {
      // corrected telos: negative depths are valid and must be kept; strict: depth+1
      const t = STRICT ? bumpText(depS[0].text, 1) : '-1.5';
      newDepth = Number(t); edits.push({ ...depS[0], text: t });
    }
    const o2 = safeRun(run, replaceSpans(raw, edits));
    if (!o2 || !close(o2.magnitude, newMag, 1e-9)) return false;
    if (newDepth !== null && !close(o2.depth_km, newDepth, 1e-9)) return false;
    if (!sameExcept(out, o2, Object.keys(out).filter(k => !['event_id', 'latitude', 'longitude', 'timestamp_utc', 'place'].includes(k)))) return false;
  }

  // R3 coordinates: negating the lat and lon tokens negates latitude and longitude
  if (latS.length === 1 && lonS.length === 1 && latS[0].start !== lonS[0].start && out.latitude !== 0 && out.longitude !== 0) {
    const o2 = safeRun(run, replaceSpans(raw, [{ ...latS[0], text: negText(latS[0].text) }, { ...lonS[0], text: negText(lonS[0].text) }]));
    if (!o2 || !close(o2.latitude, -out.latitude, 1e-9) || !close(o2.longitude, -out.longitude, 1e-9) || !only(o2, ['latitude', 'longitude'])) return false;
  }

  // R4 origin time: moving the origin-time token one day earlier moves timestamp_utc by -24h
  const tc = a.dates.filter(c => isoSec(c.ms) === out.timestamp_utc);
  const shifted = tc.length ? shiftDates(raw, tc, -1) : null;
  if (shifted) {
    const o2 = safeRun(run, shifted);
    if (!o2 || o2.timestamp_utc !== isoSec(Date.parse(out.timestamp_utc) - DAY_MS) || !only(o2, ['timestamp_utc'])) return false;
  }

  // R5 significance follows the "sig" field
  if (typeof a.sig.val === 'number' && Number.isInteger(a.sig.val) && a.sig.val < 2500) {
    const o2 = safeRun(run, replaceSpans(raw, [{ start: a.sig.start, end: a.sig.end, text: String(a.sig.val + 1) }]));
    if (!o2 || o2.significance !== a.sig.val + 1 || !only(o2, ['significance'])) return false;
  }
  return true;
}
